# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3becb858e77aec9a6be6535813e7e6a8103895cf90f5ed153d096a29fe9befef6f97ce03a40a808549a085931aeba269e12798d9abb3eb6e0099c1bbd993cac5

test:
  secret_key_base: e92603e517a76e49b61d6c56a67225e52fe1b44969e3883c8ab5395441e71fe6b3548e870e9b47931343bb7ffe469fa78ac6abc4a1d9045671da5dbcd0ef1a85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
